---
title: "Methods for computing pivot probabilities"
author: "Andy Eggers"
date: "28 August 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```


## Overall motivation and plan 

Define pivot events and show how to calculate them in a general way, not limited to one voting system. 

## Pivot events and pivot probabilities 

Consider an election involving $K$ candidates. Let $\mathcal{B}$ denote the set of admissible ballots, with $x$ referring to one of those ballots. The voting system is anonymous (i.e. it treats each voter's ballot equally), so an election outcome can be represented as a vector $\mathbf{v}$ of ballot shares, with element $v_x$ denoting the share of voters submitting ballot $x$; $\mathbf{v}$ lives on the $|\mathcal{B}|$-dimensional unit simplex $\mathbb{S}^{|\mathcal{B}|}$, with $v_x \in [0,1]$ for all ballots and $\sum \mathbf{v} = 1$.

Pivot events are subsets of election results where a single ballot can affect the outcome; a specific pivot event is the subset of election results where a single ballot can affect the outcome in a distinct way. More formally, let $w(x \mid \mathbf{v})$ be a function indicating which candidate wins at a given outcome $\mathbf{v}$ when an additional ballot $x$ is submitted. Pivot events are election outcomes where $w(x \mid \mathbf{v})$ is non-degenerate, i.e. its output depends on $x$. A specific pivot event is the subset of election outcomes with a common distinct mapping $w(x \mid \mathbf{v})$. 

<!-- Suppose, for example, there are three candidates $A$, $B$, and $C$; voters can submit ballots $a$, $b$, or $c$; and $\mathbf{v}$ is such that $A$ wins unless an additional ballot $b$ is submitted, in which case $b$ wins. Then $w(x \mid \mathbf{v})$ is  -->
<!-- \begin{align} -->
<!-- a \rightarrow& A \\ -->
<!-- b \rightarrow& B \\ -->
<!-- c \rightarrow& A \\ -->
<!-- \end{align} -->
<!-- We can partition $\mathbb{S}^{|\mathcal{B}|}$ such that each subset has a single unique mapping $w(x \mid \mathbf{v})$. Each subset in which $w(x \mid \mathbf{v})$ is non-degenerate is a distinct *pivot event*.   -->

The probability of a pivot event occurring is referred to as the *pivot probability*. Suppose an election outcome $\mathbf{v}$ is the realization of a random variable $\mathbf{V}$ with associated distribution function $f_{\mathbf{V}}(\mathbf{v})$.  
Then if $E$ is the pivot event of interest, 
<!-- and $f(\matbf{v})$ denotes the distribution over election outcomes,  -->
the pivot probability can be written  
\[
\int_{E} f(\mathbf{v}) \, d\mathbf{v}.
\]

In what follows we will assume that $\mathbf{V}$ is a continuous random variable, so that $f_{\mathbf{V}}(\mathbf{v})$ is a probability density function. Assuming $\mathbf{V}$ is continuous rather than discrete means that exact ties do not occur, which simplifies notation. It also allows us to do integration XXX. Also I think it means we can focus on binary relations?  
<!-- It also allows us to use parametric functions  approximate pivot probabilities with  -->
<!-- More importantly, it means that the calculation of pivot probabilities is a problem of integration rather than combinatorics. -->

In commonly used voting systems, pivot events are "nearly hyperplanes" -- that is, they  

I thought I had an algorithm for discovering all of the pivot probabilities. Start with the win conditions for an arbitrary candidate $a$ for the given voting system; in general, the winning conditions for a candidate in a voting system will be the union of one or more sets of inequalities on the vote shares, with each inequality pertaining to the comparison of a pair of candidates. For each set of inequalities, and each inequality comparing $a$ and $b$, narrowly reverse the $a$ and $b$ comparison. If some other specific candidate is the winner given $a$'s other win conditions, you have identified conditions for a pivot event. If $a$ remains the winner given $a$'s other win conditions, this is not a pivot event. If instead the identity of the winner depends on further conditions (i.e. conditions not part of $a$'s win conditions), then enumerate the possible conditions; each set of conditions (win conditions plus any extra conditions) that produce a winner other than $a$ corresponds to a pivot event. Having enumerated the conditions for pivot events involving a reversal of $a$ and $b$, you can re-index the candidates to get all pivot events. 

I thought this algorithm would not uncover pivot event $ab.cb$ in IRV. The win conditions for $a$ are $v_a > v_c$, $v_b > v_c$, $v_a + v_{ca} > v_b + v_{cb}$ and $v_a > v_b$, $v_c > v_b$, $v_a + v_{ba} > v_c + v_{bc}$. For the first set we narrowly reverse the second-round condition (because that's the one involving $b$) and get $ab2$.  For the second set we narrowly reverse the first-round condition $v_a > v_b$, in which case $a$ is eliminated but the winner is ambiguous. The possibilities are $v_b + v_{ab} > v_c + v_{ac}$, in which case $b$ wins and we have $ab.ab$, or $v_b + v_{ab} < v_c + v_{ac}$, in which case $c$ wins and we have $ab.ac$. But because we start from a candidate's win conditions we wouldn't get $ab.cb$. It seems that the rule "start from win conditions and reverse the $a$-$b$ condition" doesn't produce all pivot events. 

What about doing further reversals? If we narrowly reverse $v_c > v_b$, then again the winner is ambiguous. The possibilities are $v_a + v_{ca} > v_b + v_{cb}$, in which case the winner remains $a$ and it's not a pivot event, or $v_a + v_{ca} < v_b + v_{cb}$, in which case the winner is $b$ and it's pivot event $bc.ac$. So by including this reversal, we get $ab2$, $ab.ab$, $ab.ac$, and $bc.ac$ from $a$'s win conditions. And presumably applying the same rule to other pairs we would get $ab.cb$ from another pair. But what is the rule really? If we're not just reversing rules involving $a$ and $b$, then from $a$'s win conditions we would also get $ac2$ (second set), $ac.ac$, $ac.ab$, and $bc.ba$. So I think we have an algorithm that is overbroad, i.e. it gets the same pivot event more than once. 



defined by a system of inequalities and one near-equality, where the near-equality ensures that one ballot could change the outcome. For example, in a plurality contest where $v_i$ is candidate $i$'s vote share, the pivot event where a single ballot could elect $b$ instead of $a$ satisfies the conditions $v_a > v_i \, \forall \, i$ and $v_a - v_b < \frac{1}{n}$, where $n$ is the size of the electorate. (In words, a single ballot could change the winner from $a$ to $b$ if $a$ is leading but $b$ is less than vote vote behind.)  Thus (as noted by Hoffman 1983) pivot events tend to be "thin". This allows 

We can therefore approximate 


## Pivot probabilities


<!-- integrating a continuous function rather than a combinatorial problem.    -->


Let $E$ denote a pivot event of interest. 

In practice, the conditions for a pivot event include a set of inequalities and one near-equality. For example, in a plurality contest where $v_i$ is candidate $i$'s vote share, the pivot event where a single ballot could elect $b$ instead of $a$ satisfies the conditions $v_a > v_i \, \forall \, i$ and $v_a - v_b < \frac{1}{n}$. Let $\mathcal{L}_e$ denote the locus of points where these inequalities are satisfied and the near-equality is satisfied with equality. Then we can approximate the pivot probability as 
\[
\frac{1}{n} \int_{E} f(\mathbf{v}) \, d\mathbf{v}.
\]




## Motivation: pivot events and pivot probabilities

Pivot events are election outcomes in which a single vote can change the election outcome. A pivot probability is the probability of a given pivot event occuring. Computing pivot probabilities is important for determining the optimal (strategic) vote, for computing how much a voter gains by voting strategically rather than sincerely, and for assessing a voting system's susceptibility to strategic voting.

[More on pivot events -- examples?]


## Voting rules and win conditions 

Consider a voting system to elect a single winner from among $K$ candidates. Let $\mathcal{B}$ denote the set of admissible ballots, with $|\mathcal{B}| = B$; let $v_b$ denote the share of all voters casting ballot $b$, with $v_b \in [0,1] \, \forall \, b \in \mathcal{B}$ and $\sum_{i \in \mathcal{B}} v_i = 1$. 

A voting system that is anonymous (meaning that it only the count of ballots matters, not who submitted them) and neutral (meaning that it treats each candidate equally) can be characterized by defining the set of admissible ballots $\mathcal{B}$ and a set of *win conditions*, which are linear inequalities on $\mathbf{v}$ such that a given candidate wins. 

For example, plurality is the voting system where each admissible ballot names one candidate (so that $v_i$ is the share of votes for candidate $i$) and candidate $a$ wins if 
\[v_a > v_j \, \forall \, j \neq a.\]
(Note that we ignore ties here to avoid tedious notation: this is harmless if we assume that vote shares are drawn from a continuous probability distribution.)[^simplify_fn] 

[^simplify_fn]: An alternative way to simplify exposition is to assume a fixed rule for determining the winner when two candidates receive the same vote share, such as lexicographic precedence. 

In the broader class of positional methods such as Borda count, voters submit rankings of candidates and each candidate $i$ receives a score $s_i$ that depends on how many of each ranking she receives and how much each ranking is worth. For example, given $k$ candidates, a $k$th-place ranking is worth $K - k$ points in Borda count; in anti-plurality, it is worth 0 points if $k = K$ and 1 otherwise; in plurality it is worth 1 point if $k = 1$ and 0 otherwise.) Then candidate $a$ wins if 
\[s_a > s_j \, \forall \, j \neq a.\]
<!-- and each candidate is assigned a score based on  -->
<!-- Borda count is the voting system where each voter submits a ranking of candidates, candidate $i$'s score (given three candidates $i$,$j$, and $k$) is $s_i = v_{ijk} + v_{ikj} + \frac{1}{2}\left(v_{jik} + v_{kij}\right)$, and candidate $a$ wins if -->
<!-- \begin{align} -->
<!-- s_a >& s_b  \qquad \text{and} \nonumber \\  -->
<!-- s_a >& s_c.  -->
<!-- \end{align} -->

Instant-runoff voting (IRV, also known by other names including ranked-choice voting, the alternative vote system, and the single-transferrable vote) is a voting system where each voter submits a ranking of candidates and (given three candidates $a$, $b$, and $c$) candidate $a$ wins if
\begin{align}
v_{abc} + v_{acb} >&  v_{cab} + v_{cba} \\ 
v_{bac} + v_{bca} >&  v_{cab} + v_{cba}  \\ 
v_{abc} + v_{acb} + v_{cab} >&  v_{bac} + v_{bca} + v_{cba} \\
\text{or}& \\
v_{abc} + v_{acb} >&  v_{bac} + v_{bca} \\  
v_{cab} + v_{cba} >&  v_{bac} + v_{bca} \\  
v_{abc} + v_{acb} + v_{bac} >&  v_{cab} + v_{cba} + v_{bca}. 
\end{align}

A Condorcet method is a voting system where each voter submits a ranking of candidates and (given three candidates $a$, $b$, and $c$) candidate $a$ is the Condorcet winner if 
\begin{align}
v_{abc} + v_{acb} + v_{cab} >&  v_{bac} + v_{bca} + v_{cba}  \\ 
v_{abc} + v_{acb} + v_{bac} >&  v_{cab} + v_{cba} + v_{bca}. 
\end{align}
Typically a Condorcet method would specify a rule for determining who wins if there is no Condorcet winner. In the Kemeny-Young method for three candidates, for example, the candidate with the narrowest loss is the winner. That is, $a$ wins if \begin{align}
v_{abc} + v_{acb} + v_{cab} >&  v_{bac} + v_{bca} + v_{cba} \\ 
v_{abc} + v_{acb} + v_{bac} >&  v_{cab} + v_{cba} + v_{bca}  \\
\text{or}& \\
v_{abc} + v_{acb} + v_{cab} >&  v_{bac} + v_{bca} + v_{cba}  \\ 
v_{bac} + v_{bca} + v_{abc} >& v_{cab} + v_{cba} + v_{acb}  \\ 
v_{cab} + v_{cba} + v_{bca} >& v_{abc} + v_{acb} + v_{bac}  \\
v_{abc} + v_{acb} + v_{bac} >& v_{bac} + v_{bca} + v_{cba} \\
v_{abc} + v_{acb} + v_{bac} >& v_{cab} + v_{cba} + v_{acb}  \\ 
\text{or}&  \\ 
v_{abc} + v_{acb} + v_{cab} <&  v_{bac} + v_{bca} + v_{cba}  \\ 
v_{bac} + v_{bca} + v_{abc} <& v_{cab} + v_{cba} + v_{acb} \\ 
v_{cab} + v_{cba} + v_{bca} <& v_{abc} + v_{acb} + v_{bac} \\
v_{abc} + v_{acb} + v_{cab} >& v_{bac} + v_{bca} + v_{abc} \\
v_{abc} + v_{acb} + v_{cab} >& v_{cab} + v_{cba} + v_{bca}. 
\end{align}
The first pair of conditions handles the case where $a$ is the Condorcet winner. The second set of conditions handles the case where there is a forward cycle ($a$ beats $b$, $b$ beats $c$, $c$ beats $a$) and $a$'s loss to $c$ is better than $b$'s loss to $a$ and $c$'s loss to $b$. The third set of conditions handles the case where there is a reverse cycle ($a$ loses to $b$, $b$ loses to $c$, $c$ loses to $a$) and $a$'s loss to $b$ is better than $b$'s loss to $c$ and $c$'s loss to $a$.



## Defining pivot events by setting a win condition to equality

<!-- Generally, a locus is a set of points satisfying a set of conditions.  -->
In any neutral and anonymous voting system, every pivot event can be represented as an alteration of the win conditions in which one condition is set to equality. The type of alteration that is necessary depends on the voting system. 

<!-- In plurality and other positional methods (including Borda count), all pivot events can be represented by converting one of the win conditions into an equality. In elimination systems like IRV and Condorcet systems, we need to add further conditions.    -->

<!-- In IRV and other elimination systems, for some pivot events we need to add one or more conditions indicating what would happen if the putative winning candidate were eliminated. In Condorcet systems we also need to specify   -->

In any positional method (including plurality) we can estimate the probability of pivot event $ab$, where a single vote could change the winner from $a$ to $b$ (or vice versa), by integrating $f(\mathbf{v})$ over the set of points where 
<!-- one pivot event in plurality is a near-tie between $a$ and $b$ such that a single vote could change the winner from $b$ to $a$ or vice versa. This pivot event can be represented by  -->
\begin{align}
s_a =& s_b  \\
s_a >& s_j \, \forall \, j \neq a, b
\end{align}
and dividing by $n$, the size of the electorate. 

In an IRV election there are two types of pivot events. In one type, which Eggers and Nowacki refer to as "second-round pivot events", the final count (after all other candidates have been eliminated) is a near tie, such that a single ballot could change the winner. Given three candidates ($a$ $b$ and $c$), the probability of second-round pivot event $ab2$ can be estimated by integrating $f(\mathbf{v})$ over the set of points where
\begin{align}
v_{abc} + v_{acb} >&  v_{cab} + v_{cba} \\ 
v_{bac} + v_{bca} >&  v_{cab} + v_{cba}  \\ 
v_{abc} + v_{acb} + v_{cab} =&  v_{bac} + v_{bca} + v_{cba}
\end{align}
and dividing by $n$. 

The other type of IRV pivot event takes place before the final round of counting: two candidates are nearly tied for last place in a given round, such that one vote could determine which one advances and thereby determine who wins the election. In a three-candidate election, there are three such pivot events involving each pair of candidates. At one pivot event (which Eggers & Nowacki call $ab.ab$), $a$ and $b$ are tied for last in first-place votes, and $a$ would win if $a$ advanced while $b$ would win if $b$ advanced. We can estimate this pivot probability by integrating $f(\mathbf{v})$ over the set of points where 
\begin{align}
v_{abc} + v_{acb} =&  v_{bac} + v_{bca} \\ 
v_{cab} + v_{cba} >&  v_{abc} + v_{acb}  \\ 
v_{abc} + v_{acb} + v_{bac} >&  v_{cab} + v_{cba} + v_{bca} \\ 
v_{bac} + v_{bca} + v_{abc} >&  v_{cab} + v_{cba} + v_{acb}  
\end{align}
and dividing by $n$. The other two closely related pivot events are $ab.ac$, where $a$ would win if $a$ advanced while $c$ would win if $b$ advanced, and $ab.cb$, where $c$ would win if $a$ advanced while $b$ would win if $b$ advanced. We can obtain the locus for the first of these pivot events by reversing the last inequality in the above set of conditions and we can obtain the locus for the second of these pivot events by reversing the third inequality in the above set of conditions. 

Finally, consider a three-candidate election using the Kemeny method. There are two types of pivot events for each pair of candidates. In one type, the pairwise comparison of $a$ and $b$ is a near tie, while both candidates defeat each of the remaining candidates in pairwise comparisons. In the three-candidate case the corresponding locus is defined by 
\begin{align}
v_{abc} + v_{acb} + v_{cab} =&  v_{bac} + v_{bca} + v_{cba} \\ 
v_{abc} + v_{acb} + v_{bac} >&  v_{cab} + v_{cba} + v_{bca} \\ 
v_{bac} + v_{bca} + v_{abc} >&  v_{cab} + v_{cba} + v_{acb}.
\end{align}
In the other type, there is a Condorcet cycle in which $a$ and $b$ lose by nearly equal margins (and by less than other candidates involved in the cycle). 
The forward cycle occurs where 
\begin{align}
v_{abc} + v_{acb} + v_{cab} >& v_{bac} + v_{bca} + v_{cba}  \\ 
v_{bac} + v_{bca} + v_{abc} >& v_{cab} + v_{cba} + v_{acb}  \\ 
v_{cab} + v_{cba} + v_{bca} >& v_{abc} + v_{acb} + v_{bac}
\end{align}
in which case a decisive $a$-$b$ tie occurs where  
\begin{align}
v_{abc} + v_{acb} + v_{bac} =& v_{bac} + v_{bca} + v_{cba} \\
v_{abc} + v_{acb} + v_{bac} >& v_{cab} + v_{cba} + v_{acb},  \\ 
\end{align}
while the reverse cycle appears where 
\begin{align}
v_{abc} + v_{acb} + v_{cab} <&  v_{bac} + v_{bca} + v_{cba}  \\ 
v_{bac} + v_{bca} + v_{abc} <& v_{cab} + v_{cba} + v_{acb} \\ 
v_{cab} + v_{cba} + v_{bca} <& v_{abc} + v_{acb} + v_{bac} 
\end{align}
in which case a decisive $a$-$b$ tie occurs where 
\begin{align}
v_{abc} + v_{acb} + v_{cab} =& v_{bac} + v_{bca} + v_{abc} \\
v_{abc} + v_{acb} + v_{cab} >& v_{cab} + v_{cba} + v_{bca}. 
\end{align}

## Some doubts at this point 

I was interested in the idea that you can do a minimal tweak to winning conditions and get the pivot probabilities. Reverse one inequality and change the winner? In positional methods this works because  This is true of positional methods. It is not true of 

## Estimating pivot probabilities 




